eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  data:
    mongodb:
      host: localhost #ec2-35-154-155-195.ap-south-1.compute.amazonaws.com
      port: 27017
      username: mongo-admin
      password: mongo-admin
      database: role-service-db
      authentication-database: admin23
server:
  servlet:
    context-path: /role-service

