spring:
  data:
    mongodb:
      host: 13.233.111.215 #ec2-35-154-155-195.ap-south-1.compute.amazonaws.com
      port: 27017
      username: mongo-admin
      password: mongo-admin
      database: role-service-db
      authentication-database: admin
server:
  servlet:
    context-path: /role-service
