spring:
  data:
    mongodb:
      host: ec2-35-154-155-195.ap-south-1.compute.amazonaws.com
      port: 27017
      username: root
      password: root
      database: bill-payment
      authentication-database: admin
server:
  port: 8000
  servlet:
    context-path: /bps
