spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: root
      database: bill-payment
      authentication-database: admin
server:
  port: 8000
  servlet:
    context-path: /bps
